# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Anthony Burke
email:
description: > # this means to ignore newlines until "baseurl:"
  For now this site is just meant as a place for me to reflect and remember
  the things I am learning about startups, engineering, leading, managing,
  and large corporations.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://anthonyjburke.com" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown
